# Generated by Django 5.1.7 on 2025-04-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unemployment', models.FloatField()),
                ('coincident', models.FloatField()),
                ('leading_price', models.FloatField()),
                ('esi', models.FloatField(db_column='ESI')),
                ('export_price', models.FloatField()),
                ('current_account', models.FloatField()),
                ('gdp', models.FloatField(db_column='GDP')),
                ('land_price_change', models.FloatField()),
                ('ccsi', models.FloatField(db_column='CCSI')),
                ('manufacturing_capacity_utilization', models.FloatField()),
                ('us_policy_rate', models.FloatField()),
                ('kosdaq_index', models.FloatField()),
                ('capital_account', models.FloatField()),
                ('us_industrial_production', models.FloatField()),
                ('us_consumer_sentiment', models.FloatField()),
                ('us_cpi', models.FloatField(db_column='us_CPI')),
                ('economic_growth_rate', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('datetime', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeSeriesData',
        ),
    ]
