# Generated by Django 5.1.7 on 2025-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_data_delete_timeseriesdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='InterestRateData',
        ),
        migrations.AlterModelTable(
            name='interestratedata',
            table='data',
        ),
    ]
