# Generated by Django 5.1.7 on 2025-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_rename_data_interestratedata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestRateData',
            new_name='Data',
        ),
    ]
